---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-storage
      containers:
      - name: redis
        image: redis:7
        args: ["--appendonly", "yes"]
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
          - name: redis-storage
            mountPath: /data
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"