kind: Secret
apiVersion: v1
metadata:
  name: synapse-db-secret
  namespace: synapse
type: Opaque
data:
  database: c3luYXBzZQ==
  host: MTAuMzAuMS4xMDU=
  password: TTRYN3k5NEdhWkg2QnZOOWNHenY=
  port: NTQzMg==
  user: Z3JleW1hbg==