apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-config
  namespace: synapse
data:
  homeserver.yaml: |-
    server_name: "greyman.network"
    public_baseurl: https://greyman.services/
    pid_file: /data/homeserver.pid
    web_client_location: https://app.greyman.network
    serve_server_wellknown: true
    listeners:
      - port: 8008
        type: http
        tls: false
        x_forwarded: true
        resources:
          - names: [client]
            compress: false
      - port: 9093
        type: http
        resources:
          - names: [replication]
      - type: metrics
        port: 9090
    worker_replication_secret: "o8DtHe4LFJjWM#z6tm4%^2oU9T#Uwo"
    run_background_tasks_on: background_worker1
    update_user_directory_from_worker: user-directory-worker-0
    notify_appservices_from_worker: notify-appservice-worker-0
    media_instance_running_background_jobs: media-worker-0
    start_pushers: false
    pusher_instances:
      - pusher-worker-0
      - pusher-worker-1
      - pusher-worker-2
    redis:
      enabled: true
      host: redis.synapse.svc
      port: 6379
    delete_stale_devices_after: 1y
    admin_contact: 'mailto:admin@greyman.network'
    mau_stats_only: true
    database:
      name: psycopg2
      args:
        cp_min: 5
        cp_max: 10
        keepalives_idle: 10
        keepalives_interval: 10
        keepalives_count: 3
    log_config: "/data/log.config"
    media_store_path: /data/media_store
    enable_media_repo: false
    max_upload_size: 50M
    media_retention:
      local_media_lifetime: 1y
      remote_media_lifetime: 21d
    url_preview_enabled: true
    url_preview_ip_range_blacklist:
      - '127.0.0.0/8'
      - '10.0.0.0/8'
      - '172.16.0.0/12'
      - '192.168.0.0/16'
      - '100.64.0.0/10'
      - '192.0.0.0/24'
      - '169.254.0.0/16'
      - '192.88.99.0/24'
      - '198.18.0.0/15'
      - '192.0.2.0/24'
      - '198.51.100.0/24'
      - '203.0.113.0/24'
      - '224.0.0.0/4'
      - '::1/128'
      - 'fe80::/10'
      - 'fc00::/7'
      - '2001:db8::/32'
      - 'ff00::/8'
      - 'fec0::/10'
    enable_registration: true
    enable_registration_captcha: true
    recaptcha_public_key: 6LcNE1EiAAAAABLdosztplPtRCkJGRgKHU_btXqy
    recaptcha_private_key: 6LcNE1EiAAAAABVJ1ufCmEF13_Jrz7iMbPO85q7e
    registration_shared_secret: "X;Mp+pz,9;w0mWheVBHxKQI&DgpazxAgMO&eICF94g.Pcbg:DX"
    allow_guest_access: false
    default_identity_server: https://identity.greyman.network
    auto_join_rooms:
      - "#announcements:greyman.network"
      - "#welcome:greyman.network"
    user_directory:
      enabled: true
      search_all_users: true
      prefer_local_users: true
    enable_metrics: true
    report_stats: false
    macaroon_secret_key: "D50;O#IHU+sCUtM&Ju3BsJAQ;l^ELheNYK-gLxHRxO29f=DC*2"
    form_secret: "e#XzGTBAeS3NRHDodr:Hm72s&_;oqs3;O-+25Un#y3&kPWkEcp"
    signing_key_path: "/data/signing.key"
    trusted_key_servers:
      - server_name: "matrix.org"
    suppress_key_server_warning: true
    federation_domain_whitelist:
      - greyman.services
    send_federation: false
    email:
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_user: admin@greyman.network
      smtp_pass: zVKz2l^FN8IOOua1E1xlzREvvm6X6w
      enable_tls: true
      app_name: "Greyman Network"
      notif_from: system@greyman.network
      client_base_url: https://app.parrhesia.dev
  signing.key: |-
    ed25519 a_XFJT SKnVvJAnYwJM0P/nKU3NBA4AcOiqyWfXzSy2/94Tb8Q
  log.config: |-
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
    loggers:
      synapse.storage.SQL:
        level: INFO
    root:
      level: INFO
      handlers: [console]
    disable_existing_loggers: false
