---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: synapse-main
  namespace: synapse
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: (Host(`www.greyman.services`) || Host(`greyman.services`)) && (
        PathPrefix(`/.well-known/matrix/server`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/user/{(.*)}/filter`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/thirdparty/protocols`) ||
        PathPrefix(`/_matrix/client/{(api/v1|r0|v3|unstable)}/pushrules`) ||
        PathPrefix(`/_matrix/client/{(api/v1|r0|v3|unstable)}/rooms/{(.*)}/typing`) ||
        PathPrefix(`/_matrix/client/{(api/v1|r0|v3|unstable)}/rooms/{(.*)}/forget`) ||
        PathPrefix(`/_matrix/client/{(api/v1|r0|v3|unstable)}/rooms/{(.*)}/report`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/sendToDevice`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/rooms/{(.*)}/receipt`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/rooms/{(.*)}/relations`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/rooms/{(.*)}/read_markers`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/register/available`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/register/email`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/directory/room`) ||
        PathPrefix(`/_synapse/admin/v1/account_validity/validity`) ||
        PathPrefix(`/_synapse/admin/v1/background_updates/status`) ||
        PathPrefix(`/_synapse/admin/v1/background_updates/status`) ||
        PathPrefix(`/_synapse/admin/v1/background_updates/start_job`) ||
        PathPrefix(`/_synapse/admin/v1/event_reports`) ||
        PathPrefix(`/_synapse/admin/v1/purge_history`) ||
        PathPrefix(`/_synapse/admin/v1/purge_history_status`) ||
        PathPrefix(`/_synapse/admin/v1/register`) ||
        PathPrefix(`/_synapse/admin/v1/registration_tokens`) ||
        PathPrefix(`/_synapse/admin/v1/join`) ||
        PathPrefix(`/_synapse/admin/v1/rooms`) ||
        PathPrefix(`/_synapse/admin/v2/rooms`) ||
        PathPrefix(`/_synapse/admin/v1/send_server_notice`) ||
        PathPrefix(`/_synapse/admin/v1/statistics/users/media`) ||
        PathPrefix(`/_synapse/admin/v2/users`) ||
        PathPrefix(`/_synapse/admin/v1/whois`) ||
        PathPrefix(`/_synapse/admin/v1/deactivate`) ||
        PathPrefix(`/_synapse/admin/v1/reset_password`) ||
        PathPrefix(`/_synapse/admin/v1/users`) ||
        PathPrefix(`/_synapse/admin/v1/username_available`) ||
        PathPrefix(`/_synapse/admin/v1/auth_providers`) ||
        PathPrefix(`/_synapse/admin/v1/server_version`) ||
        PathPrefix(`/_matrix/client/{(r0|v3|unstable)}/account/3pid`))
      kind: Rule
      priority: 12
      services:
        - name: synapse-replication
          port: 8008
    - match: (Host(`www.greyman.services`) || Host(`greyman.services`))
      kind: Rule
      priority: 5
      services:
        - name: synapse-replication
          port: 8008
  tls:
    secretName: greyman-services-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: synapse
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https