apiVersion: v1
kind: ConfigMap
metadata:
  name: background-worker-config
  namespace: synapse
data:
  worker.yaml: |
    worker_app: synapse.app.generic_worker
    worker_name: background_worker1
    worker_replication_host: synapse-replication.synapse.svc
    worker_replication_http_port: 9093
    worker_listeners:
      - type: metrics
        port: 9090