---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-media
  namespace: synapse
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi