---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sydent
  namespace: sydent
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi