apiVersion: v1
kind: ConfigMap
metadata:
  name: sydent-config
  namespace: sydent
data:
  sydent.conf: |-
    [DEFAULT]
    server.name = identity.parrhesia.dev
    log.path = /data/sydent.log
    log.level = INFO
    pidfile.path = /data/sydent.pid
    terms.path =
    address_lookup_limit = 10000
    templates.path = res
    brand.default = matrix-org
    enable_v1_associations = true
    delete_tokens_on_bind = true
    ip.blacklist =
    ip.whitelist =
    db.file = /data/sydent.db
    clientapi.http.bind_address = ::
    clientapi.http.port = 8090
    internalapi.http.bind_address = ::1
    internalapi.http.port =
    replication.https.certfile =
    replication.https.cacert =
    replication.https.bind_address = ::
    replication.https.port = 4434
    obey_x_forwarded_for = False
    federation.verifycerts = True
    client_http_base =
    email.from = Sydent Validation <noreply@parrhesia.dev>
    email.subject = Your Validation Token
    email.invite.subject = %(sender_display_name)s has invited you to chat
    email.invite.subject_space = %(sender_display_name)s has invited you to a space
    email.smtphost = localhost
    email.smtpport = 25
    email.smtpusername =
    email.smtppassword =
    email.hostname =
    email.tlsmode = 0
    email.default_web_client_location = https://app.parrhesia.dev
    email.third_party_invite_username_obfuscate_characters = 3
    email.third_party_invite_domain_obfuscate_characters = 3
    bodytemplate = Your code is {token}
    username =
    password =
    ed25519.signingkey =

    [general]

    [db]

    [http]

    [email]

    [sms]

    [crypto]
    ed25519.signingkey = ed25519 0 RJx2suKgr3+UOL9jWH30e1hvw7BEPq6VpBLS39985pw

